### ISSUE TITLE
Cannot build a20-olinuxino-lime2 image.

### ISSUE THREAD

**Issue by salabaz** [bashrc/freedombone#75] opened 2017-10-12 20:05 UTC
When I try to build the Image, everything works fine until I get this error message. I was following this guide "https://freedombone.net/homeserver.html"

```
fetching: http://registry.npmjs.org/npm/-/npm-4.0.5.tgz
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Error: could not get uid/gid
[ 'nobody', 1000 ] 

    at /tmp/npm.16273/package/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Socket.<anonymous> (internal/child_process.js:338:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:490:12)

Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Error: could not get uid/gid
[ 'nobody', 1000 ]

    at /tmp/npm.16273/package/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:207:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:862:16)
    at Socket.<anonymous> (internal/child_process.js:338:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:490:12)

It worked
+ '[' '!' -f /tmp/user/0/tmpQ54uOm/build/usr/bin/npm ']'
+ echo 'npm was not installed'
npm was not installed
+ exit 5290462
EEEK! Something bad happened...
Command failed: /etc/freedombone/image-customise /tmp/user/0/tmpQ54uOm/build build/freedombone-min-2017-10-12_a20-olinuxino-lime2-armhf.img

```

**Comment by bashrc** [comment] 2017-10-13 08:52
Ah, I think I also saw this while trying to build a mesh image for beaglebone. Will investigate.

**Comment by bashrc** [comment] 2017-10-14 18:15
So as of 5ee805326526f9df902769b6a950be7fcdff55f6 I think this is now fixed. There were multiple problems, but the main one was a regression in the nodejs install due to trying to combine the mesh install with the server version.

There are some lime2 images now available at https://freedombone.net/downloads/current

**Closed** 2017-10-15 16:08 UTC
Labels: bug
